
services:
  pytorch:
    image: nvcr.io/nvidia/pytorch:24.01-py3
    container_name: pytorch
    stdin_open: true
    tty: true
    ipc: host
    volumes:
       - ./:/bench
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ulimits:
      memlock: -1
      stack: 67108864