
services:
  pytorch:
    build: .
    container_name: pytorch
    stdin_open: true
    tty: true
    ipc: host
    pid: host
    user: "${UID}:${GID}"
    group_add:
      - "${MEMBERS_GID}"
    volumes:
       - ./:/bench
       - ${CUDA_MPS_PIPE_DIRECTORY}:${CUDA_MPS_PIPE_DIRECTORY}
       - /scratch/lhblago:/scratch/lhblago
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - CUDA_MPS_PIPE_DIRECTORY=${CUDA_MPS_PIPE_DIRECTORY}
      - CUDA_VISIBLE_DEVICES=0
      - HF_HOME=/bench/tmp
    ulimits:
      memlock: -1
      stack: 67108864